#!/usr/bin/env python
# coding: utf-8
# TST list
# (C) 2016 Dalton Serey / UFCG

from __future__ import print_function
from __future__ import unicode_literals

import sys

import tstlib as tst

def main():

    # read arguments
    fromserver = tst.pop_flag(sys.argv, 'update', short='u')

    # read config
    config = tst.Config()
    if 'activities' not in config or fromserver:
        # get list from server
        server = tst.Server()
        activities = server.get('/api/activities', exit_on_fail=True).json()
        config['activities'] = activities
        config.save()
    else:
        activities = config['activities']

    for a in sorted(activities, key=lambda a:a['name']):
        if a['owner'] == config['user']:
            tst.cprint(tst.LCYAN, a['name'])
        else:
            tst.cprint(tst.LGREEN, a['name'] + tst.RESET + " (%s)" % a['owner'])

# main
if __name__ == "__main__":
    main()
