#!/usr/bin/env bash
# TST gentests
# (C) 2018 Dalton Serey / UFCG

LRED="\033[1;31m"
LBLUE="\033[1;34m"
LCYAN="\033[1;36m"
LGREEN="\033[1;32m"
LYELLOW="\033[1;33m"
RESET="\033[0m"

function print {
    COLOR=$2
    if [[ "$COLOR" == "" ]]; then
        COLOR=$NORMAL
    fi
    >&2 echo -n -e $COLOR"$1"$RESET
}

# leave on first error
set -e

FILE="specs.yaml"
print $LCYAN"generating tests based on specs.yaml\n"$RESET 
gen2.py $FILE

if [[ $1 == "-r" && -f "$2" ]]; then
    print $LCYAN"running $2 to generate output\n"$RESET 
    tst -o tests $2 > tst_.json
    mv tst_.json tst.json
    tst $2
fi
