#!/usr/bin/env python
# coding: utf-8
# TST-Online Checkout
# (C) 2016 Dalton Serey / UFCG

from __future__ import print_function
from __future__ import unicode_literals

import sys

import tstlib as tst

def main():

    # read tst.json and activity
    tstjson = tst.read_tstjson(quit_on_fail=True)
    kind = tstjson['kind']
    if kind != 'activity':
        tst.cprint(tst.LRED, "This command does not apply to %ss" % kind)
        sys.exit()

    server = tst.Server()
    url = '/api/activity/%d' % tstjson['iid']
    patch = [{
        'op': 'replace',
        'path': '/state',
        'value': 'enabled'
    }]
    response = server.patch(url, payload=patch, exit_on_fail=True).json()
    print(response)


# main
if __name__ == "__main__":
    config = tst.Config()
    main()
