#!/usr/bin/env bash
# TST completion
# (C) 2018 Dalton Serey / UFCG

LRED="\033[1;31m"
LBLUE="\033[1;34m"
LCYAN="\033[1;36m"
LGREEN="\033[1;32m"
LYELLOW="\033[1;33m"
RESET="\033[0m"

function print {
    COLOR=$2
    if [[ "$COLOR" == "" ]]; then
        COLOR=$NORMAL
    fi
    >&2 echo -n -e $COLOR"$1"$RESET
}

if [ ! -t 1 ]; then
    # the script was executed as eval or in pipe
    cat $(which tst.completion.sh)
else
    # the script was executed directly from terminal
    if [[ -z "$TST_COMPLETION_STATUS" ]]; then
        STATUS=$LRED"OFF"
    else
        STATUS=$LGREEN"ON"
    fi
    print $LCYAN"tst completion is $LGREEN$STATUS\n"
    print "---\n"
    print "To toggle on/off, use:\n"
    print '  eval "$(tst completion)"\n\n'
    print "To add to ~/.profile or ~/.bashrc use:\n"
    print '  source $(which tst.completion.sh)\n'
fi
