#!/usr/bin/env python
# coding: utf-8
# TST delete
# (C) 2016 Dalton Serey / UFCG

from __future__ import print_function
from __future__ import unicode_literals

import sys

import tstlib as tst

def main():

    # read tst.json and activity
    tstjson = tst.read_tstjson(quit_on_fail=True)
    kind = tstjson['kind']
    if kind != 'activity':
        tst.cprint(tst.LRED, "This command does not apply to %ss" % kind)
        sys.exit()

    state = tstjson['state']
    if state == 'new':
        tst.cprint(tst.LRED, "This activity is not saved")
        sys.exit()

    if state == 'deleted':
        tst.cprint(tst.LRED, "This activity has already been deleted")
        sys.exit()

    if state not in ('draft', 'disabled'):
        tst.cprint(tst.LRED, "Cannot delete enabled activity")
        sys.exit()

    # dispatch request
    server = tst.Server()
    url = '/activity/%d' % tstjson['iid']
    response = server.delete(url, exit_on_fail=True)
    tst.save_tstjson({
        "files": tstjson.get('files', {}),
        "name": tstjson.get('name', "unknown"),
        "kind": "activity",
        "state": "new",
        "iid": None
    })
    tst.cprint(tst.LCYAN, "Activity successfully deleted")


# main
if __name__ == "__main__":
    main()
