#!/usr/bin/env bash
# coding: utf-8
# (c) 2016 Dalton Serey, UFCG
#
# Update tst CLI scripts.
if [ "$1" == "--one-line-help" ]; then
    echo "update tst"
    exit
fi

if [ "$1" == "--pre-release" ]; then
    bash -c "$(curl -q -sSL https://raw.githubusercontent.com/daltonserey/tst/develop/etc/install.sh)" -s --update --pre-release
else
    bash -c "$(curl -q -sSL https://raw.githubusercontent.com/daltonserey/tst/master/etc/install.sh)" -s --update
fi
